artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/vipinvsist/MLFlow-End-to-End-implementation/raw/refs/heads/main/data/train_data.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    unzip_data-dir: artifacts/data_ingestion/Train-Set.csv
    STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
    root_dir: artifacts\data_transformation
    data_path: artifacts/data_injestion/Train-Set.csv


model_trainer:
    root_dir: artifacts\model_trainer
    train_data_path: C:\ML_Projects\MLflow_Implementation\MLFlow-End-to-End-implementation\artifacts\data_transformation\train.csv
    test_data_path: C:\ML_Projects\MLflow_Implementation\MLFlow-End-to-End-implementation\artifacts\data_transformation\test.csv
    model_name: model.joblib

