artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/vipinvsist/MLFlow-End-to-End-implementation/raw/refs/heads/main/data/train_data.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    unzip_data-dir: artifacts/data_ingestion/Train-Set.csv
    STATUS_FILE: artifacts/data_validation/status.txt